name: Verify API Connection

on:
  workflow_run:
    workflows: ["Deploy Frontend to GitHub Pages"]
    types:
      - completed
  workflow_dispatch:

jobs:
  test-api-connection:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test API Health Endpoint
        run: |
          echo "Testing API health endpoint..."
          # Check if URL ends with a slash and adjust path accordingly
          if [[ "${{ secrets.REACT_APP_API_URL }}" == */ ]]; then
            url="${{ secrets.REACT_APP_API_URL }}health"
          else
            url="${{ secrets.REACT_APP_API_URL }}/health"
          fi
          echo "Using URL: ${url}"
          response=$(curl -s -o response.txt -w "%{http_code}" ${url})
          if [ "$response" -eq 200 ]; then
            echo "✅ API health endpoint is working!"
            cat response.txt
          else
            echo "❌ API health endpoint returned status $response"
            cat response.txt
            echo "This could be because the health endpoint is at a different path."
            echo "Trying alternative endpoint at /api/health..."
            
            if [[ "${{ secrets.REACT_APP_API_URL }}" == */ ]]; then
              url="${{ secrets.REACT_APP_API_URL }}api/health"
            else
              url="${{ secrets.REACT_APP_API_URL }}/api/health"
            fi
            
            response=$(curl -s -o response.txt -w "%{http_code}" ${url})
            if [ "$response" -eq 200 ]; then
              echo "✅ Alternative API health endpoint is working!"
              cat response.txt
            else
              echo "❌ Both health endpoints failed. Please check the API configuration."
              exit 1
            fi
          fi

      - name: Test Forex Status Endpoint
        run: |
          echo "Testing forex status endpoint..."
          # Check if URL ends with a slash and adjust path accordingly
          if [[ "${{ secrets.REACT_APP_API_URL }}" == */ ]]; then
            url="${{ secrets.REACT_APP_API_URL }}api/v2/forex/status"
          else
            url="${{ secrets.REACT_APP_API_URL }}/api/v2/forex/status"
          fi
          echo "Using URL: ${url}"
          response=$(curl -s -o response.txt -w "%{http_code}" ${url})
          if [ "$response" -eq 200 ]; then
            echo "✅ Forex status endpoint is working!"
            cat response.txt
          else
            echo "❌ Forex status endpoint returned status $response"
            cat response.txt
            echo "This could be because the endpoint has a different path structure."
            echo "Trying alternative endpoint..."
            
            if [[ "${{ secrets.REACT_APP_API_URL }}" == */ ]]; then
              url="${{ secrets.REACT_APP_API_URL }}api/forex/status"
            else
              url="${{ secrets.REACT_APP_API_URL }}/api/forex/status"
            fi
            
            response=$(curl -s -o response.txt -w "%{http_code}" ${url})
            if [ "$response" -eq 200 ]; then
              echo "✅ Alternative forex status endpoint is working!"
              cat response.txt
            else
              echo "❌ Both forex status endpoints failed. Continuing to next test."
              # Not failing the workflow as endpoints might have changed
            fi
          fi

      - name: Test DB Status Endpoint
        run: |
          echo "Testing database status endpoint..."
          # Check if URL ends with a slash and adjust path accordingly
          if [[ "${{ secrets.REACT_APP_API_URL }}" == */ ]]; then
            url="${{ secrets.REACT_APP_API_URL }}api/db-status"
          else
            url="${{ secrets.REACT_APP_API_URL }}/api/db-status"
          fi
          echo "Using URL: ${url}"
          response=$(curl -s -o response.txt -w "%{http_code}" ${url})
          if [ "$response" -eq 200 ]; then
            echo "✅ Database status endpoint is working!"
            cat response.txt
          else
            echo "❌ Database status endpoint returned status $response"
            cat response.txt
            echo "This could be because the endpoint has a different path structure."
            echo "Trying alternative endpoint..."
            
            if [[ "${{ secrets.REACT_APP_API_URL }}" == */ ]]; then
              url="${{ secrets.REACT_APP_API_URL }}api/database/status"
            else
              url="${{ secrets.REACT_APP_API_URL }}/api/database/status"
            fi
            
            response=$(curl -s -o response.txt -w "%{http_code}" ${url})
            if [ "$response" -eq 200 ]; then
              echo "✅ Alternative database status endpoint is working!"
              cat response.txt
            else
              echo "❌ Both database status endpoints failed."
              echo "Warning: Database connection may have issues but workflow will continue."
              # Not failing the workflow as this might be acceptable
            fi
          fi

      - name: Summary
        run: |
          echo "API Connection Test Summary"
          echo "=========================="
          echo "These tests help verify that your frontend can connect to your backend API."
          echo "If any tests failed, please check:"
          echo "1. Your API is properly deployed to Vercel"
          echo "2. The REACT_APP_API_URL secret is correct"
          echo "3. Your API endpoints are correctly configured"
